oc_platform_homepage:
    path:     /
    defaults: { _controller: OCPlatformBundle:Hypair:Index }

video_page:
    path: /video
    defaults: {_controller: OCPlatformBundle:Hypair:Video}

reservation_page:
    path: /reservation
    defaults: {_controller: OCPlatformBundle:Hypair:Reservation}

photo_page:
    path:     /photo
    defaults: {_controller: OCPlatformBundle:Hypair:Photo}

propos_page:
    path:     /propos
    defaults: {_controller: OCPlatformBundle:Hypair:Propos}

admin_page:
    path:     /administration
    defaults: { _controller: OCPlatformBundle:Hypair:Administration }

ajout_photo_page:
    path:     /addPhoto
    defaults:
            _controller: OCPlatformBundle:AddPhoto:add

ajout_video_page:
    path:     /addVideo
    defaults:
            _controller: OCPlatformBundle:AddVideo:add

ajout_page:
    path:     /add
    defaults: { _controller: OCPlatformBundle:Hypair:Add }
#    requirements:
#            id:   hypairball/admin

login:
    path: /login
    defaults:
        _controller: OCUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout